namespace Properties
{
    internal class Program
    {
        static void OldMain()
        {
            Class1 obj = new Class1();
             //obj.i = 100;
            obj.Seti(100);

            Console.WriteLine(obj.Geti());

            //obj.i = ++obj.i + obj.i++ - obj.i-- - --obj.i;
        }

        static void Main()
        {
            Class2 obj = new Class2();
            obj.I = 100;  //set
            Console.WriteLine(obj.I);  //get

            obj.P1 = "Vikram";
            Console.WriteLine(obj.P1);

            //obj.P2 = "a";
            Console.WriteLine(obj.P2);

            obj.P3 = "aaa";
            Console.WriteLine(obj.P3);

            obj.P4 = "bbb";
            Console.WriteLine(obj.P4);

            obj.P5 = "aaa";
            Console.WriteLine(obj.P5);
        }
    }

    public class Class1
    {
        private int i;
        public void Seti(int VALUE)
        {
            if(VALUE <=100)
                i = VALUE;
            else
                Console.WriteLine("invalid value");
        }
        public int Geti() { return i; }
    }
    public class Class2
    {
        private int i;
        //property
        public int I
        {
            set 
            { 
                if(value <= 100)
                    i = value;
                else
                    Console.WriteLine("invalid value");
            }
            get { return i; }
        }
        private string p1="default";
        public string P1
        {
            set 
            { 
                if(value!="")
                    p1 = value;
                else
                    Console.WriteLine("Cannot be blank");
            }
            get { return p1; }
        }
        //read only
        private string p2 = "default2";
        public string P2
        {
            get { return p2; }
        }
        private string p3 = "default";
        public string P3
        {
            set
            {
                p3 = value;
            }
            get 
            { 
                return p3; 
            }
        }
        public string P4; //class level variable is also called field

        //auto property
        //code is generated by the compiler
        //compiler generates the code for get and the set
        //compiler generates the code for the private variable
        public string P5 { get; set; }
    }
}
